version: '3'

services:
  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc-mwl
    ports:
      - "104:4242"     # DICOM port (standard PACS port)
      - "105:4242"     # MWL also uses same DICOM port
      - "8042:8042"    # Web interface
    environment:
      # Enable plugins
      - ORTHANC__PLUGINS=["libModalityWorklist.so", "libServeFolders.so"]
      
      # Basic Orthanc config
      - ORTHANC__NAME=SmartBoxOrthanc
      - ORTHANC__DICOM_AET=ORTHANC
      - ORTHANC__DICOM_PORT=4242
      
      # Enable and configure Modality Worklist
      - ORTHANC__WORKLISTS__ENABLE=true
      - ORTHANC__WORKLISTS__DATABASE=/var/lib/orthanc/worklists
      - ORTHANC__WORKLISTS__FILTER_ISSUER_AET=false
      
      # Configure DICOM modalities (SmartBox can connect)
      - ORTHANC__DICOM_MODALITIES={"SMARTBOX":["SMARTBOX","host.docker.internal",104]}
      
      # Disable authentication for testing
      - ORTHANC__AUTHENTICATION_ENABLED=false
      
      # Enable all transfer syntaxes for compatibility
      - ORTHANC__ACCEPTED_TRANSFER_SYNTAXES=["1.2.840.10008.1.2","1.2.840.10008.1.2.1","1.2.840.10008.1.2.2","1.2.840.10008.1.2.4.50","1.2.840.10008.1.2.4.51","1.2.840.10008.1.2.4.57","1.2.840.10008.1.2.4.70","1.2.840.10008.1.2.4.80","1.2.840.10008.1.2.4.81","1.2.840.10008.1.2.4.90","1.2.840.10008.1.2.4.91","1.2.840.10008.1.2.4.92","1.2.840.10008.1.2.4.93","1.2.840.10008.1.2.5"]
      
      # Enable DICOM server features
      - ORTHANC__DICOM_SERVER_ENABLED=true
      - ORTHANC__DICOM_ALWAYS_ALLOW_ECHO=true
      - ORTHANC__DICOM_ALWAYS_ALLOW_STORE=true
      - ORTHANC__DICOM_CHECK_CALLED_AET=false
      
      # Storage settings
      - ORTHANC__STORAGE_DIRECTORY=/var/lib/orthanc/db
      - ORTHANC__INDEX_DIRECTORY=/var/lib/orthanc/db
      
      # Enable verbose logging for debugging
      - ORTHANC__VERBOSE_ENABLED=true
      - ORTHANC__TRACE_ENABLED=false
      
    volumes:
      - ./orthanc-storage:/var/lib/orthanc/db
      - ./worklists:/var/lib/orthanc/worklists
      - ./orthanc-config:/etc/orthanc:ro  # Optional: for custom config
      
    restart: unless-stopped
    networks:
      - pacs-network

networks:
  pacs-network:
    driver: bridge