version: '3'
services:
  orthanc:
    image: jodogne/orthanc:latest
    container_name: orthanc-test
    ports:
      - "104:104"    # DICOM C-STORE
      - "105:105"    # DICOM MWL
      - "8042:8042"  # HTTP Web UI
    environment:
      - ORTHANC__NAME=Orthanc Test Server
      - ORTHANC__DICOM_PORT=104
      - ORTHANC__DICOM_AET=ORTHANC
      - ORTHANC__REMOTE_ACCESS_ALLOWED=true
      - ORTHANC__DICOM_CHECK_CALLED_AET=false
      - ORTHANC__UNKNOWN_SOP_CLASS_ACCEPTED=true
      # MWL Settings
      - ORTHANC__WORKLISTS__ENABLE=true
      - ORTHANC__WORKLISTS__DATABASE=/var/lib/orthanc/worklists
      - ORTHANC__WORKLISTS__PORT=105
      - ORTHANC__WORKLISTS__FILTER_ISSUER_AET=false
      # DICOM Modalities
      - ORTHANC__DICOM_MODALITIES={"smartbox":["SMARTBOX","host.docker.internal",104]}
    volumes:
      - ./orthanc-storage:/var/lib/orthanc/db
      - ./orthanc-worklists:/var/lib/orthanc/worklists