// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dicom} from '../models';

export function CaptureImage(arg1:string):Promise<string>;

export function ExportDicom(arg1:string):Promise<string>;

export function GetCameras():Promise<Array<main.Camera>>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function OpenDicomFolder():Promise<void>;

export function Quit():Promise<void>;

export function SetPatientInfo(arg1:dicom.PatientInfo):Promise<void>;

export function SetStudyInfo(arg1:dicom.StudyInfo):Promise<void>;
