// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureImage(arg1) {
  return window['go']['main']['App']['CaptureImage'](arg1);
}

export function ExportDicom(arg1) {
  return window['go']['main']['App']['ExportDicom'](arg1);
}

export function GetCameras() {
  return window['go']['main']['App']['GetCameras']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function OpenDicomFolder() {
  return window['go']['main']['App']['OpenDicomFolder']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetPatientInfo(arg1) {
  return window['go']['main']['App']['SetPatientInfo'](arg1);
}

export function SetStudyInfo(arg1) {
  return window['go']['main']['App']['SetStudyInfo'](arg1);
}
